---

  - name: install packages
    when: (ansible_distribution == "Debian" or ansible_distribution == "Ubuntu")
    apt:
      name:
        - 'nginx'
        - 'python3-pip'
        - 'unzip'
        - 'ufw'

      state: present

    register: task_result
    until: task_result is success
    retries: 10
    delay: 2


  - name: install certbot
    when: (leEmail is defined and ansible_distribution == "Debian" or ansible_distribution == "Ubuntu")
    apt:
      name: certbot
      state: present
    register: task_result
    until: task_result is success
    retries: 10
    delay: 2
