---

  - name: install packages
    when: (ansible_distribution == "CentOS" or ansible_distribution == "EL")
    yum:
      name:
        - 'nginx'
        - 'python-pip'
        - 'libselinux-python'
        - 'unzip'
        - 'firewalld'
      state: present


    register: task_result
    until: task_result is success
    retries: 10
    delay: 2

  - name: install certbot
    when: (leEmail is defined and ansible_distribution == "EL" or ansible_distribution == "CentOS")
    yum:
      name: certbot
      state: present
    register: task_result
    until: task_result is success
    retries: 10
    delay: 2

  - name: enable Firewalld
    when: (ansible_distribution == "EL" or ansible_distribution == "CentOS")
    service:
      name: firewalld
      state: started
      enabled: yes
